export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const STEP_ONE = 'STEP_ONE';
export const STEP_ONE_SUCCESS = 'STEP_ONE_SUCCESS';
export const STEP_ONE_FAILURE = 'STEP_ONE_FAILURE';

export const STEP_TWO = 'STEP_TWO';
export const STEP_TWO_SUCCESS = 'STEP_TWO_SUCCESS';
export const STEP_TWO_FAILURE = 'STEP_TWO_FAILURE';

export const RECOVERY_PASSWORD = "RECOVERY_PASSWORD";
export const RECOVERY_PASSWORD_SUCCESS = "RECOVERY_PASSWORD_SUCCESS";
export const RECOVERY_PASSWORD_FAILURE = "RECOVERY_PASSWORD_FAILURE";

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const DASHBOARD = 'DASHBOARD';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';



export const ADD_FOOD = 'ADD_FOOD';
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
export const ADD_FOOD_FAILURE = 'ADD_FOOD_FAILURE';


export const ADD_EXERCISE = 'ADD_EXERCISE';
export const ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS';
export const ADD_EXERCISE_FAILURE = 'ADD_EXERCISE_FAILURE';

export const EXERCISE_LOG = 'EXERCISE_LOG';
export const EXERCISE_LOG_SUCCESS = 'EXERCISE_LOG_SUCCESS';
export const EXERCISE_LOG_FAILURE = 'EXERCISE_LOG_FAILURE';


export const FAVORITE = "FAVORITE";
export const FAVORITE_SUCCESS = "FAVORITE_SUCCESS";
export const FAVORITE_FAILURE = "FAVORITE_FAILURE";

export const ADD_PROGRESS = 'ADD_PROGRESS';
export const ADD_PROGRESS_SUCCESS = 'ADD_PROGRESS_SUCCESS';
export const ADD_PROGRESS_FAILURE = 'ADD_PROGRESS_FAILURE';


export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';



