const Images = {
    signBg1: require('../../assets/images/Bitmap.png'),
    signBg2: require('../../assets/images/Bitmap1.png'),
    food: require('../../assets/images/food.png'),
    shoe: require('../../assets/images/shoe.png'),
    water: require('../../assets/images/water.png'),
    logo: require('../../assets/images/logo.png'),
    dp1: require('../../assets/images/1.png'), 
    dp2: require('../../assets/images/2.png'),
    dp3: require('../../assets/images/3.png'),
    dp4: require('../../assets/images/4.png'),
    dp5: require('../../assets/images/5.png'),
    dp6: require('../../assets/images/6.png'),
    dp7: require('../../assets/images/7.png'),
    dp8: require('../../assets/images/8.png'),
    dp9: require('../../assets/images/9.png'),  
    bulb: require('../../assets/images/bulb.png'),
    heading:require('../../assets/images/heading.png'),
    rateus: require('../../assets/images/rateus.png'),
    quicktips: require('../../assets/images/quick_tips.png'),
    star: require('../../assets/images/star.png'),  
    bell: require('../../assets/images/bell.png'), 
     circle: require('../../assets/images/circle.png'), 
    addImageBg: require('../../assets/images/addImageBg.png'),
    bgSplash: require('../../assets/images/bgSplash.png'),
    bgExerciseFab: require('../../assets/images/bgExerciseFab.png'),
    bgFoodFab: require('../../assets/images/bgFoodFab.png'),
    logoSplash: require('../../assets/images/SplashLogo.png'),
   
    approvePic: require('../../assets/images/aproveimage.png'),
    foodImage: require('../../assets/images/Bitmap32.png'),
    backImage: require('../../assets/images/backImage.png'),


}
export default Images;