const Icons = {
    plus: require("../../assets/icons/+.png"),
    add: require("../../assets/icons/add.png"),
    apple: require("../../assets/icons/apple.png"),
    barChart: require("../../assets/icons/bar-chart.png"),
    barChart1: require("../../assets/icons/bar-chart1.png"),
    barCode: require("../../assets/icons/barcode-product.png"),
    breakfast: require("../../assets/icons/breakfast.png"),
    calendar: require("../../assets/icons/calendar.png"),
    comment: require("../../assets/icons/chat-comment.png"),
    checkMark: require("../../assets/icons/check-mark.png"),
    chicken: require("../../assets/icons/chicken.png"),
    dumbbell: require("../../assets/icons/dumbbell.png"),
    dumbbell2: require("../../assets/icons/dumbbell2.png"),
    envelope: require("../../assets/icons/envelope.png"),
    envelope1: require("../../assets/icons/envelope1.png"),
    fb: require("../../assets/icons/fb_icon.png"),
    female: require("../../assets/icons/female.png"),
    femaleActive: require("../../assets/icons/female2.png"),
    femaleDisable: require("../../assets/icons/femaleDisable.png"),
    fitness: require("../../assets/icons/fitness.png"),
    snack2: require("../../assets/icons/Group2.png"),
    lunch: require("../../assets/icons/Group21.png"),
    height: require("../../assets/icons/height.png"),
    arrowBack: require("../../assets/icons/left-arrow1.png"),
    leg: require("../../assets/icons/leg.png"),
    search: require("../../assets/icons/magnifying-glass.png"),
    maleDisable: require("../../assets/icons/male.png"),
    maleActive: require("../../assets/icons/maleActive.png"),
    meal: require("../../assets/icons/meal.png"),
    padLock: require("../../assets/icons/padlock.png"),
    camera: require("../../assets/icons/photo-camera.png"),
    camera1: require("../../assets/icons/photo-camera1.png"),
    popcorn: require("../../assets/icons/popcorn.png"),
    porkRoast: require("../../assets/icons/pork-roast.png"),
    pot: require("../../assets/icons/pot.png"),
    pregnantWoman: require("../../assets/icons/pregnant-woman.png"),
    restaurant: require("../../assets/icons/restaurant.png"),
    restaurant2: require("../../assets/icons/restaurant2.png"),
    restaurantWhite: require("../../assets/icons/restaurantw.png"),
    settings: require("../../assets/icons/settings.png"),
    home: require("../../assets/icons/home.png"),
    home2: require("../../assets/icons/home2.png"),
    snack: require("../../assets/icons/snack.png"),
    star: require("../../assets/icons/star.png"),
    star1: require("../../assets/icons/star1.png"),
    toast: require("../../assets/icons/toast.png"),
    training: require("../../assets/icons/training.png"),
    user: require("../../assets/icons/user.png"),
    user2: require("../../assets/icons/user2.png"),
    user21: require("../../assets/icons/user21.png"),
    bike: require("../../assets/icons/bike.png"),
    CheckBox: require("../../assets/icons/box.png"),
    check: require("../../assets/icons/check.png"),

    bicycle: require("../../assets/icons/bicycle.png"),
    // cereal: require("../../assets/icons/cereal.png"),
    chatPic: require("../../assets/icons/chatPic.png"),
    chef: require("../../assets/icons/chef.png"),
    compareSelectedBg: require("../../assets/icons/compareSel.png"),
    compareSelected: require("../../assets/icons/selectedComp.png"),
    edit: require("../../assets/icons/edit.png"),
    fabBtnBg: require("../../assets/icons/fabBtn.png"),
    fit: require("../../assets/icons/fit.png"),
    glass: require("../../assets/icons/glass.png"),
    leftArrow: require("../../assets/icons/left-arrow.png"),
    rightArrow: require("../../assets/icons/right-arrow.png"),
    selectedTab: require("../../assets/icons/tabSel.png"),
    // yoga: require("../../assets/icons/yoga.png"),
    sendMsg: require("../../assets/icons/sent-mail.png"),
    imageItem: require("../../assets/icons/imageItem.png"),

    cloud: require('../../assets/icons/cloudWeather.png'),
    dropDown: require('../../assets/icons/dropDown.png'),
    menuOption: require('../../assets/icons/menuOption.png'),
    sentMail: require('../../assets/icons/sent-mail.png'),
    menu: require('../../assets/icons/menu.png'),

    greyMenu: require('../../assets/icons/Groupmenu.png'),
    horizontalMenu: require('../../assets/icons/dashMenu.png'),
    waterFlow: require('../../assets/icons/waterFlow.png'),
    greenRestraunt: require('../../assets/icons/restaurantD.png'),
    bell: require('../../assets/icons/bell.png'),
    dashBarBg: require('../../assets/icons/dashBarBg.png'),
    fireWhite: require('../../assets/icons/fire1.png'),
    fireColor: require('../../assets/icons/fire2.png'),
    selectedExerciseTabs: require('../../assets/icons/selectedExerciseTabs.png'),
    purpleDot: require('../../assets/icons/Ovala4.png'),
    whiteDot: require('../../assets/icons/whitecircle.png'),
    cross: require('../../assets/icons/deletesymbol.png'),
    tick: require('../../assets/icons/greentick.png'),

    flash: require('../../assets/icons/flash.png'),
    flashOff: require('../../assets/icons/flashOff.png'),

    // Goals PNGS 
    cerealPng: require('../../assets/icons/goals/cereal.png'),
    ChefPng: require('../../assets/icons/goals/chef.png'),
    ChefPng: require('../../assets/icons/goals/chef.png'),
    fifteenPng: require('../../assets/icons/goals/15min.png'),
    ThirtyPng: require('../../assets/icons/goals/30min.png'),
    fortyfivePng: require('../../assets/icons/goals/45min.png'),
    sixtyPng: require('../../assets/icons/goals/60min.png'),
    backdropPng: require('../../assets/icons/goals/backdrop.png'),
    cloudPng: require('../../assets/icons/goals/cloud.png'),
    glassPng: require('../../assets/icons/goals/glass.png'),
    handsupPng: require('../../assets/icons/goals/handsup.png'),
    hotPng: require('../../assets/icons/goals/hot.png'),
    kneesPng: require('../../assets/icons/goals/knees.png'),
    manPng: require('../../assets/icons/goals/man.png'),
    sitPng: require('../../assets/icons/goals/sit.png'),
    thermometerPng: require('../../assets/icons/goals/thermometer.png'),
    warmPng: require('../../assets/icons/goals/warm.png'),
    yogaPng: require('../../assets/icons/goals/yoga.png'),
    // yogaPng:  require('../../assets/icons/goals/yoga.png'),
    bicepsPng: require('../../assets/icons/goals/biceps.png'),
    weightPng: require('../../assets/icons/remind.png'),
    notifyPng: require('../../assets/icons/notify.png'),
    foodPng: require('../../assets/icons/foodremind.png'),
    waterPng: require('../../assets/icons/waterremind.png'),
    exercisePng: require('../../assets/icons/exerciseremind.png'),
    card: require('../../assets/icons/card.png'),
    cardactive: require('../../assets/icons/card_active.png'),
    grid: require('../../assets/icons/grid.png'),
    gridactive: require('../../assets/icons/grid_active.png'),
     list: require('../../assets/icons/list.png'),
     listactive: require('../../assets/icons/list_active.png'),
 




    /// FoodSection

    // greenAddSvg: require('../../assets/foodSection/addIcon.svg'),
    // appleSvg: require('../../assets/foodSection/apple.svg'),
    // badgeSvg: require('../../assets/foodSection/bage.svg'),
    // progressSvg: require('../../assets/foodSection/bar-chart.svg'),
    // progressSvg: require('../../assets/foodSection/bar-chart.svg'),
    // progressGreySvg: require('../../assets/foodSection/bar-chart2.svg'),
    // blueAddSvg: require('../../assets/foodSection/blueadd.svg'),
    // breakfastSvg: require('../../assets/foodSection/breakfast.svg'),
    // checkMarkSvg: require('../../assets/foodSection/check-mark.svg'),
    // chickenSvg: require('../../assets/foodSection/chicken.svg'),
    // circleCheckSvg: require('../../assets/foodSection/circleCheck.svg'),
    // dinnerSvg: require('../../assets/foodSection/dinner.svg'),
    // dumbellSvg: require('../../assets/foodSection/dumbbell.svg'),
    // dumbellGreySvg: require('../../assets/foodSection/dumbbell2.svg'),
    // femaleGreySvg: require('../../assets/foodSection/female-worker.svg'),
    // fitnessSvg: require('../../assets/foodSection/fitness1.svg'),
    // greenAddSvg: require('../../assets/foodSection/greenadd.svg'),
    // homeSvg: require('../../assets/foodSection/home.svg'),
    // home2Svg: require('../../assets/foodSection/home2.svg'),
    // leftArrowSvg: require('../../assets/foodSection/leftarrow.svg'),
    // lunchSvg: require('../../assets/foodSection/lunch.svg'),
    // magnifyingGlassSvg: require('../../assets/foodSection/magnifyingglass.svg'),
    // maleSvg: require('../../assets/foodSection/male.svg'),
    // popcornSvg: require('../../assets/foodSection/popcorn.svg'),
    // porkRoastSvg: require('../../assets/foodSection/pork-roast.svg'),
    // restaurantSvg: require('../../assets/foodSection/restaurant.svg'),
    // restaurant2Svg: require('../../assets/foodSection/restaurant2.svg'),
    // sentMailSvg: require('../../assets/foodSection/sent-mail.svg'),
    // shoeSvg: require('../../assets/foodSection/shoe.svg'),
    // starSvg: require('../../assets/foodSection/star.svg'),
    // toastSvg: require('../../assets/foodSection/toast.svg'),
    // userSvg: require('../../assets/foodSection/user.svg'),
    // user2Svg: require('../../assets/foodSection/user2.svg'),
    // yellowstarSvg: require('../../assets/foodSection/yellowstar.svg'),


    // Goals Icons 
    // ceralSvg: require('../../assets/goalsIcons/cerealsvg.svg'),
    // chefSvg: require('../../assets/goalsIcons/chefsvg.svg'),
    // cloudSvg: require('../../assets/goalsIcons/cloudsvg.svg'),
    // handsup: require('../../assets/goalsIcons/exsvg.svg'),
    // glassSvg: require('../../assets/goalsIcons/glasssvg.svg'),
    // manSvg: require('../../assets/icons/svgs/man.svg'),
    // thermometerSvg: require('../../assets/goalsIcons/thermometersvg.svg'),
    // warmweatherSvg: require('../../assets/goalsIcons/weather1svg.svg'),
    // hotweatherSvg: require('../../assets/goalsIcons/weather1svg.svg'),
    // bicepSvg: require('../../assets/icons/svgs/weightsvg.svg'),
    // yogaSvg: require('../../assets/goalsIcons/yoga2svg.svg'),
    // sittingSvg: require('../../assets/goalsIcons/yogasvg.svg'),
    // backdropSvg: require('../../assets/goalsIcons/yogasvg3.svg'),
    // kneeSvg: require('../../assets/icons/svgs/knee.svg'),
    // fifteemMin: require('../../assets/goalsIcons/15min.svg'),
    // thirtyMin: require('../../assets/goalsIcons/30min.svg'),
    // fortyfiveMin: require('../../assets/goalsIcons/45min.svg'),
    // sixtyMin: require('../../assets/goalsIcons/60min.svg'),



    // profile

    // calendar: require('../../assets/profile/calendar.svg'),
    // envelope: require('../../assets/profile/envelope.svg'),
    // female: require('../../assets/profile/female.svg'),
    // height: require('../../assets/profile/height.svg'),
    // pregnant: require('../../assets/profile/pregnant.svg'),


    // goals

    // fifteen: require('../../assets/SVGs/icons/goals/15min.svg'),
    // thirty: require('../../assets/SVGs/icons/goals/30min.svg'),
    // fortyFive: require('../../assets/SVGs/icons/goals/45min.svg'),
    // sixty: require('../../assets/SVGs/icons/goals/60min.svg'),
    // backdrop: require('../../assets/SVGs/icons/goals/backDrop.svg'),
    // cereal: require('../../assets/SVGs/icons/goals/cereal.svg'),
    // chef: require('../../assets/SVGs/icons/goals/chef.svg'),
    // clouds: require('../../assets/SVGs/icons/goals/clouds.svg'),
    // handsOnKnee: require('../../assets/SVGs/icons/goals/handsonKneee.svg'),
    // handsup: require('../../assets/SVGs/icons/goals/handsup.svg'),
    // hotweather: require('../../assets/SVGs/icons/goals/hotweather.svg'),
    // mandrop: require('../../assets/SVGs/icons/goals/mandrop.svg'       ),
    // temp: require('../../assets/SVGs/icons/goals/temperature.svg'),
    // warmWeather: require('../../assets/SVGs/icons/goals/warmweather.svg'),
    // waterglass: require('../../assets/SVGs/icons/goals/waterglass.svg'),
    // weightLifting: require('../../assets/SVGs/icons/goals/weightlifting.svg'),
    // yoga: require('../../assets/SVGs/icons/goals/yoga.svg')


 
}

export default Icons;